export interface StorefrontTestimonial {
  id: string;
  name: string;
  city: string | null;
  rating: number;
  body: string;
  isPublished: boolean;
  isSample: boolean;
  sortOrder: number;
  createdAt: Date;
}

export const DEFAULT_STOREFRONT_TESTIMONIALS: StorefrontTestimonial[] = [
  {
    id: "tst_default_1",
    name: "Anjali R.",
    city: "Bengaluru",
    rating: 5,
    body: "The package arrived on time and in discreet cardboard packaging. The tracking updates via SMS were helpful.",
    isPublished: true,
    isSample: false,
    sortOrder: 1,
    createdAt: new Date("2026-01-01"),
  },
  {
    id: "tst_default_2",
    name: "Pooja M.",
    city: "Pune",
    rating: 5,
    body: "Ordering through the website was straightforward. Customer care responded promptly to my delivery query.",
    isPublished: true,
    isSample: false,
    sortOrder: 2,
    createdAt: new Date("2026-01-02"),
  },
  {
    id: "tst_default_3",
    name: "Sneha K.",
    city: "Kochi",
    rating: 5,
    body: "Carefully packed parcel received in good condition within three days. Appreciate the prompt dispatch.",
    isPublished: true,
    isSample: false,
    sortOrder: 3,
    createdAt: new Date("2026-01-03"),
  },
  {
    id: "tst_default_4",
    name: "Divya S.",
    city: "Hyderabad",
    rating: 4,
    body: "Clear delivery notifications and smooth checkout. The parcel was delivered on schedule.",
    isPublished: true,
    isSample: false,
    sortOrder: 4,
    createdAt: new Date("2026-01-04"),
  },
  {
    id: "tst_default_5",
    name: "Meera T.",
    city: "Jaipur",
    rating: 5,
    body: "Smooth online order process and timely courier delivery. Customer support was polite and helpful.",
    isPublished: true,
    isSample: false,
    sortOrder: 5,
    createdAt: new Date("2026-01-05"),
  },
  {
    id: "tst_default_6",
    name: "Kavita N.",
    city: "Chennai",
    rating: 5,
    body: "The dispatch was quick and the packaging was neat and sturdy. Good communication throughout.",
    isPublished: true,
    isSample: false,
    sortOrder: 6,
    createdAt: new Date("2026-01-06"),
  },
  {
    id: "tst_default_7",
    name: "Rhea S.",
    city: "Mumbai",
    rating: 5,
    body: "Prompt delivery in discreet brown box packaging. The included storage pouch is well stitched and convenient.",
    isPublished: true,
    isSample: false,
    sortOrder: 7,
    createdAt: new Date("2026-01-07"),
  },
  {
    id: "tst_default_8",
    name: "Tanvi P.",
    city: "Ahmedabad",
    rating: 5,
    body: "The order was dispatched on the same day. Tracking information was accurate and easy to follow.",
    isPublished: true,
    isSample: false,
    sortOrder: 8,
    createdAt: new Date("2026-01-08"),
  },
  {
    id: "tst_default_9",
    name: "Shreya B.",
    city: "Kolkata",
    rating: 4,
    body: "Neat packaging and clear user instructions in the package. The website was easy to navigate on mobile.",
    isPublished: true,
    isSample: false,
    sortOrder: 9,
    createdAt: new Date("2026-01-09"),
  },
  {
    id: "tst_default_10",
    name: "Aarti V.",
    city: "Delhi",
    rating: 5,
    body: "Received my package within 48 hours in South Delhi. The box arrived in clean condition with a tamper tape.",
    isPublished: true,
    isSample: false,
    sortOrder: 10,
    createdAt: new Date("2026-01-10"),
  },
  {
    id: "tst_default_11",
    name: "Nidhi G.",
    city: "Chandigarh",
    rating: 5,
    body: "Customer support promptly assisted me when choosing between sizes. Very polite team and quick response.",
    isPublished: true,
    isSample: false,
    sortOrder: 11,
    createdAt: new Date("2026-01-11"),
  },
  {
    id: "tst_default_12",
    name: "Prerna M.",
    city: "Lucknow",
    rating: 5,
    body: "Ordered the gift pack for my cousin. The box presentation is lovely and arrived in intact condition.",
    isPublished: true,
    isSample: false,
    sortOrder: 12,
    createdAt: new Date("2026-01-12"),
  },
];
